### ISSUE TITLE
How to use sign-up page?

### ISSUE THREAD

**Issue by ragasirtahk** [quizzr-cms/quizzr#5]
The sign-up page doesn't give option to register. How to use it? Also, please provide an SQL dump with two users.

The first user registered will be the admin?

**Comment by jophab** [comment]
@alpha007khatri I will add the sql file to create tables.
Sensitive data are removed.
Add users manually in the db.
Give role 10 for admin privileges .
Give role 1 for normal user.

**Comment by jophab** [comment]
Register page was not developed.
So its not there.
This project will have to go through some serious rework since it is not fully developed. 
We hope that we can come up with a better version using new technologies like angularjs or nodejs etc in future.
I think you can make things work with the sql file now added. :+1:

**Comment by ragasirtahk** [comment]
Thanks :)
Can you please provide a sign up page? Also, will the treasure hunt mode save answer logs by users? How to view logs?

**Comment by jophab** [comment]
`will the treasure hunt mode save answer logs by users? How to view logs?`
Yes. You can see it in admin panel.
But I cant work on the signup page now.
You just go through the login code and give data in db manually or create a sign up page your self.
